In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time
import cv2
%matplotlib inline

In [2]:
path = 'photo\p0\\'

corresponding_in = np.load(path+'small_corresponding_in.npy')
# corresponding_in = np.load(path+'tps_small_corresponding_in.npy')

lis =np.load(path+'small_corresponding_contours.npy')
data1 = np.load(path+'small_contours.npy')
data2 = np.load(path+'small_contours_smpl.npy')

In [3]:
for i in corresponding_in:
    print(i)

[[28 22]
 [29 22]]
[[28 23]
 [28 23]]
[[29 20]
 [30 21]]
[[29 21]
 [30 22]]
[[29 22]
 [30 23]]
[[29 23]
 [29 23]]
[[29 24]
 [28 23]]
[[30 20]
 [31 22]]
[[30 21]
 [31 23]]
[[30 22]
 [31 23]]
[[30 23]
 [30 24]]
[[30 24]
 [29 24]]
[[30 25]
 [28 24]]
[[30 26]
 [27 25]]
[[31 16]
 [30 21]]
[[31 19]
 [31 22]]
[[31 20]
 [32 23]]
[[31 21]
 [32 23]]
[[31 22]
 [32 24]]
[[31 23]
 [31 24]]
[[31 24]
 [30 25]]
[[31 25]
 [28 25]]
[[32 17]
 [31 22]]
[[32 18]
 [32 22]]
[[32 19]
 [33 23]]
[[32 20]
 [33 23]]
[[32 21]
 [33 24]]
[[32 22]
 [33 24]]
[[32 23]
 [32 25]]
[[32 24]
 [30 25]]
[[33 18]
 [34 22]]
[[33 19]
 [35 23]]
[[33 20]
 [35 24]]
[[33 21]
 [34 24]]
[[33 22]
 [33 25]]
[[33 23]
 [32 25]]
[[33 24]
 [30 25]]
[[34 19]
 [37 23]]
[[34 20]
 [36 24]]
[[34 21]
 [35 24]]
[[34 22]
 [35 25]]
[[34 23]
 [33 26]]
[[34 24]
 [31 26]]
[[34 25]
 [28 25]]
[[35 19]
 [38 23]]
[[35 20]
 [37 24]]
[[35 21]
 [37 24]]
[[35 22]
 [36 25]]
[[35 23]
 [34 26]]
[[35 24]
 [33 26]]
[[35 25]
 [30 26]]
[[35 26]
 [28 26]]
[[36 20]
 [3

 [ 98 109]]
[[ 92 113]
 [ 98 110]]
[[ 92 114]
 [ 98 111]]
[[ 92 115]
 [ 98 112]]
[[ 92 116]
 [ 98 113]]
[[ 92 117]
 [ 98 114]]
[[ 92 118]
 [ 98 115]]
[[ 92 119]
 [ 98 116]]
[[ 92 120]
 [ 98 117]]
[[ 92 121]
 [ 98 119]]
[[ 92 122]
 [ 98 120]]
[[ 92 123]
 [ 98 121]]
[[ 92 124]
 [ 98 122]]
[[ 92 125]
 [ 98 123]]
[[ 92 126]
 [ 98 124]]
[[ 92 127]
 [ 98 125]]
[[ 92 128]
 [ 98 127]]
[[ 92 129]
 [ 98 128]]
[[ 92 130]
 [ 98 129]]
[[ 92 131]
 [ 98 130]]
[[ 92 132]
 [ 98 131]]
[[ 92 133]
 [ 98 132]]
[[ 92 134]
 [ 98 133]]
[[ 92 135]
 [ 98 134]]
[[ 92 136]
 [ 98 135]]
[[ 92 137]
 [ 98 136]]
[[ 92 138]
 [ 98 137]]
[[ 92 139]
 [ 98 138]]
[[ 92 140]
 [ 98 139]]
[[ 92 141]
 [ 98 140]]
[[ 92 142]
 [ 98 141]]
[[ 92 143]
 [ 97 141]]
[[ 92 144]
 [ 97 142]]
[[ 92 145]
 [ 97 143]]
[[ 92 146]
 [ 97 144]]
[[ 92 147]
 [ 96 145]]
[[ 92 148]
 [ 96 146]]
[[ 92 149]
 [ 96 147]]
[[ 92 150]
 [ 96 148]]
[[ 92 151]
 [ 96 149]]
[[ 92 152]
 [ 96 150]]
[[ 92 153]
 [ 96 151]]
[[ 92 154]
 [ 96 152]]
[[ 92 155]
 [ 96 153]]

 [95 41]]
[[98 42]
 [95 42]]
[[98 43]
 [95 43]]
[[98 44]
 [95 44]]
[[98 45]
 [95 46]]
[[98 46]
 [95 47]]
[[98 47]
 [95 48]]
[[98 48]
 [95 49]]
[[98 49]
 [95 50]]
[[98 50]
 [95 52]]
[[98 51]
 [95 53]]
[[98 52]
 [96 54]]
[[98 53]
 [96 55]]
[[98 54]
 [96 56]]
[[98 55]
 [96 57]]
[[98 56]
 [96 59]]
[[98 57]
 [96 60]]
[[98 58]
 [96 61]]
[[98 59]
 [96 62]]
[[98 60]
 [96 63]]
[[98 61]
 [96 64]]
[[98 62]
 [96 65]]
[[98 63]
 [96 66]]
[[98 64]
 [96 67]]
[[98 65]
 [96 68]]
[[98 66]
 [96 68]]
[[98 67]
 [97 69]]
[[98 68]
 [97 70]]
[[98 69]
 [97 71]]
[[98 70]
 [97 72]]
[[98 71]
 [98 73]]
[[98 72]
 [98 74]]
[[98 73]
 [98 75]]
[[98 74]
 [98 76]]
[[98 75]
 [99 77]]
[[98 76]
 [99 77]]
[[98 77]
 [99 78]]
[[ 98  78]
 [100  79]]
[[ 98  79]
 [100  80]]
[[ 98  80]
 [100  81]]
[[ 98  81]
 [101  82]]
[[ 98  82]
 [101  83]]
[[ 98  83]
 [101  84]]
[[ 98  84]
 [101  84]]
[[ 98  85]
 [102  85]]
[[ 98  86]
 [102  86]]
[[ 98  87]
 [102  87]]
[[ 98  88]
 [102  88]]
[[ 98  89]
 [103  89]]
[[ 98  90]
 [103  90]]
[[ 98  

 [102  35]]
[[105  33]
 [102  36]]
[[105  34]
 [102  37]]
[[105  35]
 [102  38]]
[[105  36]
 [102  39]]
[[105  37]
 [102  39]]
[[105  38]
 [102  40]]
[[105  39]
 [102  41]]
[[105  40]
 [102  42]]
[[105  41]
 [102  43]]
[[105  42]
 [102  44]]
[[105  43]
 [102  45]]
[[105  44]
 [102  47]]
[[105  45]
 [102  48]]
[[105  46]
 [102  49]]
[[105  47]
 [102  50]]
[[105  48]
 [102  51]]
[[105  49]
 [102  52]]
[[105  50]
 [102  53]]
[[105  51]
 [102  54]]
[[105  52]
 [102  55]]
[[105  53]
 [102  56]]
[[105  54]
 [102  57]]
[[105  55]
 [102  58]]
[[105  56]
 [102  59]]
[[105  57]
 [102  60]]
[[105  58]
 [102  62]]
[[105  59]
 [103  63]]
[[105  60]
 [103  64]]
[[105  61]
 [103  65]]
[[105  62]
 [103  66]]
[[105  63]
 [103  67]]
[[105  64]
 [103  68]]
[[105  65]
 [103  69]]
[[105  66]
 [103  70]]
[[105  67]
 [104  71]]
[[105  68]
 [104  72]]
[[105  69]
 [104  73]]
[[105  70]
 [105  74]]
[[105  71]
 [105  75]]
[[105  72]
 [105  76]]
[[105  73]
 [105  76]]
[[105  74]
 [106  77]]
[[105  75]
 [106  78]]

 [110  52]]
[[113  51]
 [110  53]]
[[113  52]
 [110  55]]
[[113  53]
 [110  56]]
[[113  54]
 [110  57]]
[[113  55]
 [110  58]]
[[113  56]
 [110  59]]
[[113  57]
 [110  60]]
[[113  58]
 [110  61]]
[[113  59]
 [110  63]]
[[113  60]
 [110  64]]
[[113  61]
 [110  65]]
[[113  62]
 [110  66]]
[[113  63]
 [110  67]]
[[113  64]
 [110  68]]
[[113  65]
 [110  69]]
[[113  66]
 [111  70]]
[[113  67]
 [111  72]]
[[113  68]
 [111  73]]
[[113  69]
 [111  74]]
[[113  70]
 [112  75]]
[[113  71]
 [112  76]]
[[113  72]
 [112  77]]
[[113  73]
 [113  78]]
[[113  74]
 [113  79]]
[[113  75]
 [114  79]]
[[113  76]
 [114  80]]
[[113  77]
 [114  81]]
[[113  78]
 [115  82]]
[[113  79]
 [115  82]]
[[113  80]
 [115  83]]
[[113  81]
 [115  84]]
[[113  82]
 [115  84]]
[[113  83]
 [116  85]]
[[113  84]
 [116  86]]
[[113  85]
 [116  87]]
[[113  86]
 [116  88]]
[[113  87]
 [116  88]]
[[113  88]
 [116  89]]
[[113  89]
 [116  90]]
[[113  90]
 [117  91]]
[[113  91]
 [117  92]]
[[113  92]
 [117  93]]
[[113  93]
 [117  93]]

 [116 141]]
[[119 142]
 [116 142]]
[[119 160]
 [116 160]]
[[119 161]
 [115 161]]
[[119 162]
 [115 162]]
[[119 163]
 [116 163]]
[[119 164]
 [116 164]]
[[119 165]
 [116 165]]
[[119 166]
 [116 166]]
[[119 167]
 [116 167]]
[[119 168]
 [116 168]]
[[119 169]
 [116 169]]
[[120  45]
 [120  46]]
[[120  46]
 [119  47]]
[[120  47]
 [118  48]]
[[120  48]
 [118  49]]
[[120  49]
 [117  51]]
[[120  50]
 [117  52]]
[[120  51]
 [117  53]]
[[120  52]
 [117  54]]
[[120  53]
 [116  55]]
[[120  54]
 [116  56]]
[[120  55]
 [116  57]]
[[120  56]
 [116  58]]
[[120  57]
 [116  59]]
[[120  58]
 [116  60]]
[[120  59]
 [116  62]]
[[120  60]
 [116  63]]
[[120  61]
 [116  64]]
[[120  62]
 [116  65]]
[[120  63]
 [116  66]]
[[120  64]
 [116  67]]
[[120  65]
 [116  68]]
[[120  66]
 [116  70]]
[[120  67]
 [116  71]]
[[120  68]
 [116  72]]
[[120  69]
 [116  73]]
[[120  70]
 [117  74]]
[[120  71]
 [117  76]]
[[120  72]
 [117  77]]
[[120  73]
 [118  78]]
[[120  74]
 [118  79]]
[[120  75]
 [118  79]]
[[120  76]
 [119  80]]

In [4]:

depthMap =cv2.imread(path+'depthMap.png',0)

In [5]:
depthMap.shape

(220, 195)

In [6]:
# 直接将深度图的像素值作为深度值
newPng_origin = np.mat(np.zeros((depthMap.shape)))
for i in corresponding_in:
    newPng_origin[i[0][1],i[0][0]] = depthMap[i[1][1], i[1][0]]
    
for i in lis:
#     print(data1[int(i[0])][1],data1[int(i[0])][0])
    newPng_origin[data1[int(i[0])][1],data1[int(i[0])][0]] = depthMap[data2[int(i[1])][1], data2[int(i[1])][0]]
 
newPng_origin_array = newPng_origin.A
cv2.imwrite(path+"newPng_origin.png", newPng_origin_array)
# cv2.imwrite(path+"tps_newPng_origin.png", newPng_origin_array)

True

In [7]:
# import math
# # 通过斜边转化成深度值

# newPng_origin = np.mat(np.zeros((depthMap.shape)))
# for i in corresponding_in:
#     newPng_origin[i[0][1],i[0][0]] =math.sqrt(pow(depthMap[i[1][1], i[1][0]],2)-pow((x/2-i[1][1]),2)-pow((y/2-i[1][0]),2))
    
# for i in lis:
# #     math.sqrt(pow(depthMap[data2[int(i[1])][1], data2[int(i[1])][0]],2)-pow((x/2-data2[int(i[1])][1]),2)-pow((y/2-data2[int(i[1])][0]),2))
    
# #     newPng_origin[data1[int(i[0])][1],data1[int(i[0])][0]] = depthMap[data2[int(i[1])][1], data2[int(i[1])][0]]
#     newPng_origin[data1[int(i[0])][1],data1[int(i[0])][0]] =  math.sqrt(pow(depthMap[data2[int(i[1])][1], data2[int(i[1])][0]],2)-pow((x/2-data2[int(i[1])][1]),2)-pow((y/2-data2[int(i[1])][0]),2))
 
# newPng_origin_array = newPng_origin.A
# cv2.imwrite("newPng_origin.png", newPng_origin_array)